# I/O settings

output_path : "/path/to/output/"

##  source data/ output folders for run.py
image_path : "/path/to/imagefile.tif"
output_filename : "image001"

##  source data/ output folders for run_stack.py
input_path : "/path/to/imagefile.tif"


# segmentation parameters
channel_junction: 0
channel_nucleus : 1
channel_golgi : 2
channel_expression_marker : -1
estimated_cell_diameter : 100

